N_CLUSTERS_DEFAULT = 500
COMPACTNESS_DEFAULT = 20

N_BACKGROUND_SEGMENTS_DEFAULT = 25
BACKGROUND_COMPACTNESS_DEFAULT = 10

JACCARD_THRESHOLD_DEFAULT = 0.3

T_INIT_DEFAULT = 10
KL_THRESHOLD_DEFAULT = 0.8
MATCH_THRESHOLD_DEFAULT = 2 

H_DEFAULT = 1080 // 3
W_DEFAULT = 1920 // 3

N_SAMPLES = 500